### ISSUE TITLE
Add Company Commands

### ISSUE THREAD

**Issue by Nekonic** [Nekonic/Mineconomy-Core#2]
Writing company commands

- [ ] /mark company balance: Get company balance
- [ ] /mark company deposit &#60;amount>: Deposit mark to company account
- [ ] /mark company withdraw &#60;amount>: Withdraws money from a company account to add an item to inventory
- [ ] /mark company transfer <destination company> &#60;amount>: Transfer capital between companies
